name: dedop
channels:
    - conda-forge
dependencies:
    - python==3.7
    - hdf4>=4.2.13
    - netcdf4>=1.5.1.2
    - numexpr >=2.6.4
    - numpy>=1.18.1
    - scipy>=1.4.1
    - bokeh>=1.3
    - ipywidgets
    - jupyter
    - matplotlib-base>=3.1.3
    - matplotlib>=3.1.3
    - pyproj<2.0
    - tornado>=6.0
    - pip
    - pip:
          - git+https://github.com/CCI-Tools/cate.git@v2.1.1

    # for testing only
    #
    - pytest
    - pytest-cov
